require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Rails/OutputSafety:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 7
