AllCops:
  Exclude:
    - 'db/**/*'
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Rails:
  Enabled: true

BlockLength:
  Exclude:
    - spec/**/*

OutputSafety:
  Enabled: false

StringLiterals:
  EnforcedStyle: double_quotes
